name: MVP-UI
options:
  bundleIdPrefix: com.YOURNAMESPACE
  postGenCommand: pod update
packages:
  TextFieldItem:
    url: https://github.com/Vaka37/TextFieldItem
    majorVersion: 1.0.2
  Swinject:
    url: https://github.com/Swinject/Swinject.git
    majorVersion: 2.8.0
targets:
  MVP-UI:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - MVP-UI
      - CoreData.xcdatamodeld
    settings:
        base:
            SWIFT_VERSION: 5.0
            CURRENT_PROJECT_VERSION: 1.0.0
            MARKETING_VERSION: 1
            IPHONEOS_DEPLOYMENT_TARGET: "15.0"
            ENABLE_USER_SCRIPT_SANDBOXING: false
            
            INFOPLIST_KEY_UILaunchScreen_Generation: true

            ASSETCATALOG_COMPILER_GENERATE_ASSET_SYMBOLS: true
            ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: true
            GENERATE_INFOPLIST_FILE: true
            # ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: "AccentColor"
            # ASSETCATALOG_COMPILER_APPICON_NAME: "AppIcon"
    dependencies:
      - package: TextFieldItem
      - package: Swinject
    preBuildScripts:
      - script: |
                if [[ -f "${PODS_ROOT}/SwiftGen/bin/swiftgen" ]];
                  then "${PODS_ROOT}/SwiftGen/bin/swiftgen"
                else
                  echo "warning: SwiftGen is not installed. Run 'pod install --repo-update' to install it."
                fi
        name: SwiftGen
        basedOnDependencyAnalysis: false
        showEnvVars: false
    postCompileScripts:
      - script: |
                if [[ "$(uname -m)" == arm64 ]]; then
                 export PATH="/opt/homebrew/bin:$PATH"
                fi
                if which swiftformat > /dev/null; then
                 swiftformat .
                else
                 echo "warning: SwiftFormat not installed, download from https://github.com/nicklockwood/SwiftFormat"
                fi
        name: SwiftFormat
        basedOnDependencyAnalysis: false
        showEnvVars: false
      - script: |
                if [[ "$(uname -m)" == arm64 ]]; then
                 export PATH="/opt/homebrew/bin:$PATH"
                fi
                if which swiftlint > /dev/null; then
                 swiftlint
                else
                 echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
                fi
        name: SwiftLint
        basedOnDependencyAnalysis: false
        showEnvVars: false
  RecipiesMock:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - MVP-UI
      - CoreData.xcdatamodeld
    settings:
        base:
            SWIFT_VERSION: 5.0
            CURRENT_PROJECT_VERSION: 1.0.0
            MARKETING_VERSION: 1
            IPHONEOS_DEPLOYMENT_TARGET: "15.0"
            ENABLE_USER_SCRIPT_SANDBOXING: false
            
            INFOPLIST_KEY_UILaunchScreen_Generation: true

            ASSETCATALOG_COMPILER_GENERATE_ASSET_SYMBOLS: true
            ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: true
            GENERATE_INFOPLIST_FILE: true
            
            OTHER_SWIFT_FLAGS: "-D Mock"
    dependencies:
      - package: TextFieldItem
      - package: Swinject
    preBuildScripts:
      - script: |
                if [[ -f "${PODS_ROOT}/SwiftGen/bin/swiftgen" ]];
                  then "${PODS_ROOT}/SwiftGen/bin/swiftgen"
                else
                  echo "warning: SwiftGen is not installed. Run 'pod install --repo-update' to install it."
                fi
        name: SwiftGen
        basedOnDependencyAnalysis: false
        showEnvVars: false
    postCompileScripts:
      - script: |
                if [[ "$(uname -m)" == arm64 ]]; then
                    export PATH="/opt/homebrew/bin:$PATH"
                fi

                if which swiftformat > /dev/null; then
                    swiftformat .
                else
                    echo "warning: SwiftFormat not installed, download from https://github.com/nicklockwood/SwiftFormat"
                    exit 1
                fi
        name: SwiftFormat
        basedOnDependencyAnalysis: false
        showEnvVars: false
      - script: |
                if [[ "$(uname -m)" == arm64 ]]; then
                    export PATH="/opt/homebrew/bin:$PATH"
                fi

                if which swiftlint > /dev/null; then
                    swiftlint
                else
                    echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
                    exit 1
                fi
        name: SwiftLint
        basedOnDependencyAnalysis: false
        showEnvVars: false
  RecipelyTest:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - MVP-UI
      - NewtworkTests
    settings:
        base:
            SWIFT_VERSION: 5.0
            CURRENT_PROJECT_VERSION: 1.0.0
            MARKETING_VERSION: 1
            IPHONEOS_DEPLOYMENT_TARGET: "15.0"
            ENABLE_USER_SCRIPT_SANDBOXING: false
            
            INFOPLIST_KEY_UILaunchScreen_Generation: true

            ASSETCATALOG_COMPILER_GENERATE_ASSET_SYMBOLS: true
            ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: true
            GENERATE_INFOPLIST_FILE: true
            
            OTHER_SWIFT_FLAGS: "-D Mock"
    dependencies:
      - package: Swinject
      - package: TextFieldItem
    preBuildScripts:
      - script: |
                if [[ -f "${PODS_ROOT}/SwiftGen/bin/swiftgen" ]];
                  then "${PODS_ROOT}/SwiftGen/bin/swiftgen"
                else
                  echo "warning: SwiftGen is not installed. Run 'pod install --repo-update' to install it."
                fi
        name: SwiftGen
        basedOnDependencyAnalysis: false
        showEnvVars: false
    postCompileScripts:
      - script: |
                if [[ "$(uname -m)" == arm64 ]]; then
                    export PATH="/opt/homebrew/bin:$PATH"
                fi

                if which swiftformat > /dev/null; then
                    swiftformat .
                else
                    echo "warning: SwiftFormat not installed, download from https://github.com/nicklockwood/SwiftFormat"
                    exit 1
                fi
        name: SwiftFormat
        basedOnDependencyAnalysis: false
        showEnvVars: false
      - script: |
                if [[ "$(uname -m)" == arm64 ]]; then
                    export PATH="/opt/homebrew/bin:$PATH"
                fi

                if which swiftlint > /dev/null; then
                    swiftlint
                else
                    echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
                    exit 1
                fi
        name: SwiftLint
        basedOnDependencyAnalysis: false
        showEnvVars: false
  MVP-UITests:
    type: bundle.ui-testing
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - MVP-UI
      - UI-Testing
    settings:
        base:
            SWIFT_VERSION: 5.0
            CURRENT_PROJECT_VERSION: 1.0.0
            MARKETING_VERSION: 1
            IPHONEOS_DEPLOYMENT_TARGET: "15.0"
            ENABLE_USER_SCRIPT_SANDBOXING: false
            
            INFOPLIST_KEY_UILaunchScreen_Generation: true

            ASSETCATALOG_COMPILER_GENERATE_ASSET_SYMBOLS: true
            ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: true
            GENERATE_INFOPLIST_FILE: true
            
            OTHER_SWIFT_FLAGS: "-D Mock"
    dependencies:
      - package: Swinject
      - package: TextFieldItem
    preBuildScripts:
      - script: |
                if [[ -f "${PODS_ROOT}/SwiftGen/bin/swiftgen" ]];
                  then "${PODS_ROOT}/SwiftGen/bin/swiftgen"
                else
                  echo "warning: SwiftGen is not installed. Run 'pod install --repo-update' to install it."
                fi
        name: SwiftGen
        basedOnDependencyAnalysis: false
        showEnvVars: false
    postCompileScripts:
      - script: |
                if [[ "$(uname -m)" == arm64 ]]; then
                    export PATH="/opt/homebrew/bin:$PATH"
                fi

                if which swiftformat > /dev/null; then
                    swiftformat .
                else
                    echo "warning: SwiftFormat not installed, download from https://github.com/nicklockwood/SwiftFormat"
                    exit 1
                fi
        name: SwiftFormat
        basedOnDependencyAnalysis: false
        showEnvVars: false
      - script: |
                if [[ "$(uname -m)" == arm64 ]]; then
                    export PATH="/opt/homebrew/bin:$PATH"
                fi

                if which swiftlint > /dev/null; then
                    swiftlint
                else
                    echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
                    exit 1
                fi
        name: SwiftLint
        basedOnDependencyAnalysis: false
        showEnvVars: false